language: node_js
node_js:
  - "8"
addons:
  chrome: stable
services:
  - xvfb
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
before_script:
  - npm install -g @angular/cli@7.3.9
  - npm install
script:
  - npm run test-lib
sudo: required
